Codebase is tough to port to MSVC2022 (and very probably other non-gcc compiler dev platforms. Further work pending -- abandon trial of this project.
MSVC2022 reported errors, f.e.:

```
merror\internal\preprocessor_test.cc(44,3): warning C4003: not enough arguments for function-like macro invocation 'MERROR_INTERNAL_VCAT_I'
merror\internal\preprocessor_test.cc(54,3): error C2065: 'MERROR_INTERNAL_IS_VARIADIC_R_': undeclared identifier
merror\internal\preprocessor_test.cc(54,3): error C2065: 'MERROR_INTERNAL_IS_VARIADIC_C': undeclared identifier
merror\internal\preprocessor_test.cc(54,3): error C2146: syntax error: missing ')' before identifier 'MERROR_INTERNAL_DETECT_UNDERSCORE'
merror\internal\preprocessor_test.cc(54,3): error C2181: illegal else without matching if
merror\internal\preprocessor_test.cc(54,3): error C2065: 'gtest_ar_': undeclared identifier
merror\internal\preprocessor_test.cc(54,3): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to
...
```